### PR TITLE
Remove google-guava dependency

### PR DESCRIPTION
**Pull request by jbellmann**
This PR superseded #11. It's all fine there but it's possible to remove the dependency on google-guava and use Springs own 'StopWatch'-Implementation.

### CODE REVIEW

**Comment by jbellmann** [comment]
👍

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by lukasniemeier-zalando** [comment]
Are you planning a release afterwards?

**Comment by jbellmann** [comment]
Unable to merge until 'Zappr' allows me to do so.  :-(

**Comment by lukasniemeier-zalando** [comment]
Test

**Comment by jbellmann** [comment]
👍

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by jbellmann** [comment]
👍

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by jbellmann** [comment]
now it's green, yeah

**Comment by jbellmann** [comment]
@lukasniemeier-zalando  will do a release now

**Pull request merged**
