### PR TITLE
clean up code and update dependencies

### PR DESCRIPTION
**Pull request by harti2006**
Pre-PR for #23 

As discussed with @duergner this PR does all the cleanup tasks before we finally migrate to Spring Boot 2 in the next phase.

* upgrade Spring Boot to 1.5.13
* remove stups-parent from maven build because it is not maintained anymore
    * at the same time use spring-boot-starter-parent to have managed dependency and plugin management
* remove license headers from Java files
* use indentation with spaces instead of tabs consistently
* optimize imports

### CODE REVIEW

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
@harti2006 you want to approve and merge yourself?

**Comment by harti2006** [comment]
:+1:

**Comment by jbellmann** [comment]
👍

**Review by jbellmann — APPROVED** [review]
Seems I have to do this GH-Review thing. Zappr alone was not enough.

**Pull request merged**
